name: Essays & Stories
description: Brennan's journal of literature, life, and passion for furthering humanity.
meta_description: "A Personal Journal about learning by Brennan Brown."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'brenjour.github.io'
google_analytics: 'UA-54919711-1'

# Details for the RSS feed generator
url:            'brenjour.github.io'
author:         'Brennan Brown'

# My Settings

permalink: /:title
