name: Essays & Stories
description: My take on literature, life and improving the world.
meta_description: "A take on literature, life and improving the world."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'

permalink: /:title